### ISSUE TITLE
When using Auto MOD in Diving gas I am unable to select a depth greater than 40m on air

### ISSUE THREAD

**Issue by Fixer-11** [VlasovAlexey/DiveProMe#1]
With a setting of 1.40 for PPO2 bottom and a Bottom Gas of 21% O2, 0% He, MOD AUTO I am unable to select a Depth > 40m in Build Dive Profile.
If I manually set the MOD (to 56m) then I am able to select a Depth up to 56m

**Comment by VlasovAlexey** [comment]
Hi. It is feature. Automatic MOD calculation to any used mix. If you want more depth please change your PPO2 and PPN2 limits to more aggressive. Or change manually in gas list in MOD from "auto" to your depth. Not a bug.
