### ISSUE TITLE
Ascent rate has no effect (iOS-Version 10.5)

### ISSUE THREAD

**Issue by Nedial** [VlasovAlexey/DiveProMe#2]
No matter what value I enter for 'Ascent Rate', it has no effect. Only the entry of 'Ascent Deco Rate' causes a change in the calculation of the ascent time. It does not matter whether a dive is calculated with or without deco.

**Comment by VlasovAlexey** [comment]
iOS version has stopped support. Please use online version on iOS: http://divepro.me/

**Comment by VlasovAlexey** [comment]
Ascent rate bug still here. Added to pull requests.

**Comment by VlasovAlexey** [comment]
We need some explanation. The Ascent parameter works but only for multilevel dives. Please take a look at the picture below. It shows in detail which segment means what and how it works:
![image](https://user-images.githubusercontent.com/24822433/197387714-a4b58986-d6e8-4ad6-a0c1-cf81bbe6e36b.png)
