### ISSUE TITLE
‚Ascent Rate to surface‘ is missing

### ISSUE THREAD

**Issue by Nedial** [VlasovAlexey/DiveProMe#3]
To follow the recommendation to significantly reduce the ascent speed from the last stop to the surface (1m/min), a corresponding option for this is missing.

**Comment by VlasovAlexey** [comment]
Hi,
added to requests.

**Comment by VlasovAlexey** [comment]
Added "Ascent Rate to surface" parameter. Now it can be set from one meter per minute to 10 meters per minute.
