### ISSUE TITLE
"Mix Change Extra Time" don't work in version 14. Android and Windows.

### ISSUE THREAD

**Issue by nytroster** [VlasovAlexey/DiveProMe#5]
![dive](https://github.com/VlasovAlexey/DiveProMe/assets/2961576/efd4f8c2-f762-446c-9c98-58a239fbc9e2)
Set Mix Change Extra Time to 2 min.

**Comment by VlasovAlexey** [comment]
Fixed in release 14.1
Please update the application for your operating system. Or use the online version: 
https://vlasovalexey.github.io/DiveProMe/HTML_SRC/

Android 14.1 version will be available in the next couple of days.
