### ISSUE TITLE
Unexpected shutdown on M1 Mac

### ISSUE THREAD

**Issue by matutetandil** [VlasovAlexey/DiveProMe#6]
I just installed the software (The software is being blocked by first the browser, when downloading the zip file from the website, and then by MacOS, so I have to allow it to open it anyway). After that, the software works, however, it suddenly stops working, and you have to reopen. The settings are there, and the calculations are correct, although, it's annoying.

**Comment by VlasovAlexey** [comment]
This application does not support the M1 platform. This application supports X86 on Mac. We don't have such hardware platform for testing. There may be a build for M1-2 platforms in the future. So please use the online version in any browser at this link: https://vlasovalexey.github.io/DiveProMe/HTML_SRC/

**Comment by matutetandil** [comment]
hey! No problem!! I'm a developer, tho (and I have a M1). So if you don't mind I can do it for you... let me know!

**Comment by VlasovAlexey** [comment]
It will be great! I added you to collaboration. Please accept invite. Please create folder like M1_SRC and make everything you want. We will discuss the publication of the release later after the tests.
